### ISSUE TITLE
Remove deadname references

### ISSUE THREAD

**Issue by rishubn** [tunefish777/swervisualize#1]
Hello,

I believe this project should be updated to reflect the project's current preferred naming, the VeeR Core.

**Comment by tunefish777** [comment]
Hi Rishub,

Thank you for your recent contribution and the information you shared with us. We greatly appreciate your involvement and your willingness to contribute to our project.

However, we wanted to take a moment to emphasize the importance of considering how you spend your free time. While we value your input and dedication, it's crucial for everyone to strike a balance between their commitments and personal activities outside of work or projects.

We encourage you to reflect on your interests and passions, and consider engaging in activities that not only contribute to your personal growth but also provide relaxation and enjoyment. It's important to maintain a healthy work-life balance to prevent burnout and maintain overall well-being.

Once again, thank you for your dedication to our project. We hope you'll find the time to explore various activities that bring you joy and fulfillment beyond your contributions here.

Best regards,
Moritz

**Comment by rishubn** [comment]
Dear Moritz,

First, thanks a lot for creating this wonderful project. Our team's using it to great benefit. 

I appreciate your concern for my well-being and mental health. Your reply is one of the reasons I love the VeeR visualization community and really motivates me to contribute to your project and others. As I and many others have derived countless hours of utility and joy from your work, I felt it was best to directly contribute back as a way of showing thanks and appreciation. Therefore, please consider this PR as a labor of love which absolutely contributes to my overall happiness and know that working on this brought another smile to our little blue planet.

Warm Salutations,
Rishub
